name: app-ci

on:
  pull_request:
    paths:
      - "app/**"

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install --quiet

      - name: Test Run
        run: npm run app:test
